trigger:
- main

resources:
- repo: self

variables:
  imageName: custom-image
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Build Image
    pool:
      name: "RS"     # ✅ Replace with your agent pool name
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: $(imageName)
        tags: |
          $(tag)
